import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>Luke Test</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/luke-test11',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/luke-test11',
  footer: {
    text: 'Luke Test - Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – Luke Test'
    }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="Luke Test" />
      <meta property="og:description" content="Documentation for Luke Test" />
    </>
  )
}

export default config
